language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
# command to install dependencies
install: "pip install -e ."
before_script:
  - pip install -r requirements.test.txt
script: ./run-tests